/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "morohlscjcbumreawios"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vcm9obHNjamNidW1yZWF3aW9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxMDkyNzAsImV4cCI6MjA4NTY4NTI3MH0.oqSb5XgtpHIIi8j-1_9g-7Tjq0q-iMCCnrXYvD6eQ90"